In [2]:
import numpy as np

In [3]:
alist=[1,2,3,4,5,6]

In [4]:
arr=np.array(alist)

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
print (type(arr))

<class 'numpy.ndarray'>


In [7]:
np.shape(arr)

(6,)

In [8]:
mat=np.array([[1,2,3],[4,5,6]])

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.size(mat)

6

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [16]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

## 2. Random Number Generation

In [17]:
np.random.rand(5)

array([0.11015979, 0.42922886, 0.27001341, 0.04953034, 0.72930912])

In [18]:
np.random.rand(2,3)

array([[0.58693988, 0.96207375, 0.53361838],
       [0.11256424, 0.50124593, 0.99375513]])

In [19]:
def myfunc(n,p,q):
    lists=np.random.rand(n)
    lists=[x*100000%(q-p)+p for x in lists]
    return lists

In [20]:
myfunc(3,10,20)

[19.743997904995922, 13.308765108929947, 12.5966467334365]

In [21]:
np.random.randint(1,10)

9

In [22]:
np.random.randint(10,20,(2,2))

array([[14, 17],
       [14, 11]])

In [23]:
np.random.seed(555)
np.random.randint(10,20,(2,2))

array([[19, 11],
       [14, 16]])

In [24]:
## 3.Shaping 

In [25]:
## 3.Shaping 

np.arange(6)

In [26]:
arr=np.arange(6)

In [27]:
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
arr.shape

(6,)

In [29]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
arr=arr.reshape(2,3)

In [31]:
arr.max()

5

In [32]:
arr.min()

0

In [33]:
arr.mean()

2.5

In [34]:
arr.std() # standard deviation

1.707825127659933

In [35]:
## 3. Indexing and slicing

In [36]:
arr=np.arange(10,20)

In [37]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
arr[0]

10

In [39]:
arr[0:4]

array([10, 11, 12, 13])

In [40]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [41]:
newarr=arr[0:6]
newarr

array([10, 11, 12, 13, 14, 15])

In [42]:
newarr[:]=99

In [43]:
newarr

array([99, 99, 99, 99, 99, 99])

In [44]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19])

In [45]:
arrcopy=arr.copy()

In [46]:
arrcopy[0:6]=64

In [47]:
arrcopy

array([64, 64, 64, 64, 64, 64, 16, 17, 18, 19])

In [48]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19])

In [49]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
mat[0][0]

1

In [51]:
for i in range(3):
    for j in range(3):
        print(mat[i][j])

1
2
3
4
5
6
7
8
9


In [52]:
for i in range(3):
    for j in range(3):
        print(mat[i,j])

1
2
3
4
5
6
7
8
9


In [53]:
## matrix slicing

mat

In [54]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
mat[::2,::2]

array([[1, 3],
       [7, 9]])

In [57]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
mat2=mat.T

In [59]:
mat2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
mat+mat2

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [61]:
mat*mat2

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [62]:
mat2=np.arange(4).reshape(2,2)
np.linalg.inv(mat2)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [63]:
a=np.array([1,2,3])

In [64]:
b=np.array([4,5,6])

In [65]:
amag=np.linalg.norm(a) ##magnitude of a

In [66]:
bmag=np.linalg.norm(b)

In [67]:
cos_angle=np.dot(a,b)/(amag*bmag)

In [68]:
cos_angle

0.9746318461970762

In [87]:
sin_angle=np.linalg.norm(np.cross(a,b))/(amag*bmag)

In [88]:
sin_angle

0.22381412908589723